services:
  - type: web
    name: line-bot
    env: go
    buildCommand: "./bot_app"
    startCommand: "./bot_app"
    envVars:
      - key: LINE_CHANNEL_SECRET
        sync: false # 從 Render 後台設定
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: AZURE_API_KEY
        sync: false
      - key: AZURE_API_REGION
        sync: false